if (!require(tidyverse)) install.packages("tidyverse") 
if (!require(data.table)) install.packages("data.table") 
library(tidyverse)
library(data.table)
library(arules)

chen <- fread("./recomen/chennel.csv")
comp <- fread("./recomen/competitor.csv")
cust <- fread("./recomen/customer.csv")
item <- fread("./recomen/item.csv")
memb <- fread("./recomen/membership.csv")
tran <- fread("./recomen/tran.csv")
